### ISSUE TITLE
Graphic issue: Add padding between VoLTE/VoWiFi icon and Network speed indicator

### ISSUE THREAD

**Issue by anaelle-dev** [siavash79/PixelXpert#636]
# Description:
I would like to suggest an enhancement for the AOSPMods module in Magisk, specifically related to the "Show VoLTE icon when available", "Show VoWiFi icon when available", and "Enable network monitor" features.

Currently, in the stock Pixel 7 Pro May 2023 ROM, with the 2.9.0 version of the AOSPMods module, the VoLTE/VoWiFi icons and the network speed indicator are displayed close to each other in the status bar. I believe it would be beneficial to introduce some spacing between these elements for better visual separation and improved user experience.

# Screenshots:
![Screenshot](https://github.com/siavash79/AOSPMods/assets/63869398/c494aeb9-4773-449c-a22b-9d21fbdd3d60)

# AOSP Custom ROM Source:
The AOSPMods module is used in its 2.9.0 version alongside the stock Pixel 7 Pro May 2023 ROM.

#

I'm unsure whether this suggestion falls under the category of a feature request or a bug fix. However, to ensure it reaches the appropriate developers, I am posting it here. Please guide me if I should provide this suggestion elsewhere.

Thank you for considering my suggestion to enhance the AOSPMods module.

**Comment by EleoXDA** [comment]
It is neither a bug report nor a feature request. Just a graphical glitch report. We will consider it in future versions

**Comment by EleoXDA** [comment]
![Screenshot_20231227-013246.png](https://github.com/siavash79/PixelXpert/assets/27622683/e17d1c05-bc75-4b05-931a-d8098dc08308)

Looks like it is resolved with Dec security patch

**Comment by Traaanaelle** [comment]
It seems that the margin is the same thanks to Iconify, but with stock icons the problem is still present
