### ISSUE TITLE
[Bug] The canary version cannot be opened and keeps crashing

### ISSUE THREAD

**Issue by fuzhengqu** [siavash79/PixelXpert#741]
### Describe the issue

The canary version cannot be opened and keeps crashing. The stable version is working normally. I have updated three versions in a row and still cannot open it. The current version is 299.

### Steps to reproduce

The canary version cannot be opened and keeps crashing. The stable version is working normally. I have updated three versions in a row and still cannot open it. The current version is 299.

### Your device setup (Please take some time to give correct information here)

Google Pixel 5
Android 14 UP1A.231105.001
Magisk 26401
Pixel Xpert Canary-299

### Logs

Since the Pixel Xpert canary version is installed, lsposed cannot be opened now, so the log cannot be obtained.

**Comment by EleoXDA** [comment]
Something wrong in your setup. You said you updated three versions in a row. What do you mean by that? 297 298 and 299 do not work for you?

If LSposed cannot be opened, this means something wrong in its initiation or its setup in magisk manager. Be sure that LSposed is correctly installed and then report back please

**Comment by Mahmud0808** [comment]
What keeps crashing exactly? SystemUI or PixelXpert app itself? If SystemUI is crashing, then provide LSposed logs after you disable PixelXpert module and recover from crashing. LSposed keeps old logs too.

**Comment by EleoXDA** [comment]
I see no other user with this issue in latest canaries in our test group. I would say he needs to do a clean install with no other magisk or lsposed modules. Pretty sure some other module messes his device up.

**Comment by sbresin** [comment]
I have the same issue. Can't open the app, I see the toast that su was granted, but then it crashes.

291 is the last working version for me.

I am on Magisk Delta 26.1 and LSposed 1.9.2 (Zygisk) on a Pixel 5 with Android 14

Will try to logcat in the coming days.

**Comment by fuzhengqu** [comment]
[LSPosed_2023-11-21T07_55_19.566097.zip](https://github.com/siavash79/PixelXpert/files/13420381/LSPosed_2023-11-21T07_55_19.566097.zip)
[LSPosed_2023-11-21T07_55_13.724094.zip](https://github.com/siavash79/PixelXpert/files/13420379/LSPosed_2023-11-21T07_55_13.724094.zip)

**Comment by jameslawfer** [comment]
I'm having the same issue here on Magisk 26.4, LSPosed 1.9.2 and several of the latest canary builds (last tested 301). PixelXpert app crashing (as opposed to SystemUI).

**Comment by EleoXDA** [comment]
@all, please retry with only PixelXpert in magisk and LSPosed. Turn off all other modules

**Comment by fuzhengqu** [comment]
I've tried it from the beginning, but it doesn't work. Apart from LSposed and Pixel Xpert, I only have one module to enable 5G. I also deleted it and restarted the phone to test it, but it didn't work.  Only by switching to the latest official version of Pixel Xpert can it be used normally. Canary to 302 cannot be used

**Comment by Mahmud0808** [comment]
@fuzhengqu is Canary-291 working for you? Can you test if possible?

**Comment by siavash79** [comment]
What if you disable the lsposed module from magisk? I understand PixelXpert will not work if you do so, but I'm wondering if the app will open in that condition

**Comment by jameslawfer** [comment]
> @fuzhengqu @jameslawfer is Canary-291 working for you? Can you test if possible?

@Mahmud0808 confirming Canary-291 seems to function!

**Comment by Mahmud0808** [comment]
> @Mahmud0808 confirming Canary-291 seems to function!

try this one too

> What if you disable the lsposed module from magisk? I understand PixelXpert will not work if you do so, but I'm wondering if the app will open in that condition

**Comment by fuzhengqu** [comment]
> What if you disable the lsposed module from magisk? I understand PixelXpert will not work if you do so, but I'm wondering if the app will open in that condition
Pixel Xpert cannot be opened in this case either

**Comment by fuzhengqu** [comment]
> @fuzhengqu @jameslawfer is Canary-291 working for you? Can you test if possible?

Canary-291 version can not be found where to download, can you provide a download link

**Comment by jameslawfer** [comment]
> > @fuzhengqu @jameslawfer is Canary-291 working for you? Can you test if possible?
> 
> Canary-291 version can not be found where to download, can you provide a download link
> 
> 

The Canary builds can be found in the telegram group (linked in the README). I've re-uploaded that below:

[PixelXpert-canary291.zip](https://github.com/siavash79/PixelXpert/files/13445263/PixelXpert-canary291.zip)

**Comment by fuzhengqu** [comment]
> > > @fuzhengqu @jameslawfer is Canary-291 working for you? Can you test if possible?
> > 
> > 
> > Canary-291 version can not be found where to download, can you provide a download link
> 
> The Canary builds can be found in the telegram group (linked in the README). I've re-uploaded that below:
> 
> [PixelXpert-canary291.zip](https://github.com/siavash79/PixelXpert/files/13445263/PixelXpert-canary291.zip)

canary-291 can be opened and used normally

**Comment by fuzhengqu** [comment]
> So, canary-291 works, can anyone confirm if canary-292 crashes? or exactly from which version it starts crashing?

In my case, it is normal to use the latest official version 3.10, but the specific minor version number has been forgotten now. On this basis, I have tried everything from canary-297 to 302, but they cannot be opened normally. I installed canary-292 according to your request and found that it can no longer be opened normally.

**Comment by fuzhengqu** [comment]
> Please try running its APK from the path written below. Continue through the prompt about updating an existing package.
> 
> `/data/adb/modules/PixelXpert/system/priv-app/PixelXpert/PixelXpert.apk`

I found this path as you requested, but the apk cannot be installed, prompting "There was a problem parsing the package".Currently, my Pixel Xpert is version 3.2.0

**Comment by EleoXDA** [comment]
> > Please try running its APK from the path written below. Continue through the prompt about updating an existing package.
> > `/data/adb/modules/PixelXpert/system/priv-app/PixelXpert/PixelXpert.apk`
> 
> I found this path as you requested, but the apk cannot be installed, prompting "There was a problem parsing the package".Currently, my Pixel Xpert is version 3.2.0

you can try with pixelxpert/package manager menu and enable both options. it will grant you access of installing apks without signature and allowing downgrade for 5 minutes.

**Comment by fuzhengqu** [comment]
> > > Please try running its APK from the path written below. Continue through the prompt about updating an existing package.
> > > `/data/adb/modules/PixelXpert/system/priv-app/PixelXpert/PixelXpert.apk`
> > 
> > I found this path as you requested, but the apk cannot be installed, prompting "There was a problem parsing the package".Currently, my Pixel Xpert is version 3.2.0
> 
> you can try with pixelxpert/package manager menu and enable both options. it will grant you access of installing apks without signature and allowing downgrade for 5 minutes.

Sorry,I don’t quite understand the operation you are talking about.

**Comment by EleoXDA** [comment]
> > > > Please try running its APK from the path written below. Continue through the prompt about updating an existing package.
> > > > `/data/adb/modules/PixelXpert/system/priv-app/PixelXpert/PixelXpert.apk`
> > > 
> > > I found this path as you requested, but the apk cannot be installed, prompting "There was a problem parsing the package".Currently, my Pixel Xpert is version 3.2.0
> > 
> > you can try with pixelxpert/package manager menu and enable both options. it will grant you access of installing apks without signature and allowing downgrade for 5 minutes.
> 
> Sorry,I don’t quite understand the operation you are talking about.

![Screenshot_20231207-211110.png](https://github.com/siavash79/PixelXpert/assets/27622683/cda128e7-1081-4820-a13e-83e5789905b9)

![Screenshot_20231207-211107.png](https://github.com/siavash79/PixelXpert/assets/27622683/547dfb9b-cd01-4405-ae31-d99dea3edd83)

**Comment by EleoXDA** [comment]
@fuzhengqu @sbresin @jameslawfer 

Did any of you (who cannot open PixelXpert) actually tried with clean slate? Try it with latest stable OR canary.
- use standard magisk (not delta) on stable channel
- remove ALL magisk modules except LSPosed and PixelXpert
- update LSPosed to latest version from [releases](https://github.com/LSPosed/LSPosed/releases)
- Remove all LSPosed modules except PixelXpert
- Restart and grant su access if required
- See if it works or not. If not, extract LSPosed logs and share here.

I can see no apparent reason for it to not work at all

**Comment by fuzhengqu** [comment]
> @fuzhengqu @sbresin @jameslawfer
> 
> Did any of you (who cannot open PixelXpert) actually tried with clean slate? Try it with latest stable OR canary.
> 
> * use standard magisk (not delta) on stable channel
> * remove ALL magisk modules except LSPosed and PixelXpert
> * update LSPosed to latest version from [releases](https://github.com/LSPosed/LSPosed/releases)
> * Remove all LSPosed modules except PixelXpert
> * Restart and grant su access if required
> * See if it works or not. If not, extract LSPosed logs and share here.
> 
> I can see no apparent reason for it to not work at all

Please help me check the LSposed module log again. I cleared the history log and clicked Pixel Xpert again. The latest log  generated after the crash
[LSPosed_2023-12-08T21_06_10.879220.zip](https://github.com/siavash79/PixelXpert/files/13614363/LSPosed_2023-12-08T21_06_10.879220.zip)

**Comment by EleoXDA** [comment]
> > @fuzhengqu @sbresin @jameslawfer
> > Did any of you (who cannot open PixelXpert) actually tried with clean slate? Try it with latest stable OR canary.
> > 
> > * use standard magisk (not delta) on stable channel
> > * remove ALL magisk modules except LSPosed and PixelXpert
> > * update LSPosed to latest version from [releases](https://github.com/LSPosed/LSPosed/releases)
> > * Remove all LSPosed modules except PixelXpert
> > * Restart and grant su access if required
> > * See if it works or not. If not, extract LSPosed logs and share here.
> > 
> > I can see no apparent reason for it to not work at all
> 
> Please help me check the LSposed module log again. I cleared the history log and clicked Pixel Xpert again. The latest log generated after the crash [LSPosed_2023-12-08T21_06_10.879220.zip](https://github.com/siavash79/PixelXpert/files/13614363/LSPosed_2023-12-08T21_06_10.879220.zip)

Do you have only PixelXpert in LSPosed and only PixelXpert & LSPosed in magisk? I see more modules than that

**Comment by fuzhengqu** [comment]
I sent the lsposed module log to the AI analysis, can you help me to see that these problems mentioned are possible to solve the problem?The following reply:

From the error log you provided, the crash occurred in an activity called SplashScreenActivity. This activity tried to load a layout file containing a CircularProgressIndicator component, but encountered problems. The specific error is:

java
java.lang.RuntimeException: Unable to start activity ComponentInfo{sh.siava.pixelxpert/sh.siava.pixelxpert.ui.activities.SplashScreenActivity}: android.view.InflateException: Binary XML file line #52 in sh.siava.pixelxpert:layout/activity_splash_screen: Binary XML file line #52 in sh.siava.pixelxpert:layout/activity_splash_screen: Error inflating class com.google.android.material.progressindicator.CircularProgressIndicator
Here are some possible reasons for this issue:

Layout File Problem: There may be errors or incomplete attribute settings for the CircularProgressIndicator in line 52 of the XML layout file.
Dependency Library Issue: If your application has not correctly added the Google Material Design library, the CircularProgressIndicator class will not be found, causing inflation to fail.
Version Compatibility Issue: Your application may be using APIs that are incompatible with the Android version on the current device. For example, if CircularProgressIndicator was introduced in a higher version of the Android API and you run your app on a lower version of the Android system, such issues may occur.
Third-Party Module Conflict: If you're using LSPosed or other modules to modify system functionality or behavior, these modules may interfere with the normal operation of native components, leading to similar issues.
To solve this problem, you can try the following steps:

Check the XML layout file for SplashScreenActivity to ensure that the CircularProgressIndicator tag on line 52 is correct.
Make sure that your project has added the Google Material Design library as a dependency.
If you're using third-party modules, try disabling them to see if it solves the problem.
Clean and rebuild your project to clear any potential build errors.
If the above steps don't solve the problem, please provide more information like the detailed layout file content, project dependencies, etc., for further analysis.

**Comment by MrKingMichael** [comment]
I had the exact same issue on the same device which is why I made this comment. It solved the issue for me.

> Please try running its APK from the path written below. Continue through the prompt about updating an existing package.
> 
> `/data/adb/modules/PixelXpert/system/priv-app/PixelXpert/PixelXpert.apk`

**Comment by siavash79** [comment]
Okay. Clearly, devs can't reproduce the issue at their end.

So, you guys need to help tracking it

Please:
- Uninstall PX from magisk and reboot
- Check your apps, and make sure no more PX is installed. It shouldn't, but double checking won't hurt. Uninstall it if needed
- Disable lsposed module temporarily. Please disable all other magisk modules too. Reboot
- install the latest PX magisk module and reboot
- check if you can open the app. (It will ask you for root permission. Grant it)
- if you couldn't open the app, take a logcat report from the moment of app crash. Search Google to find ways to do so
- attach your logcat report, along with details of your ROM

-if the app launched as expected, enable only lsposed module and reboot. Check if the app again

**Comment by siavash79** [comment]
> I sent the lsposed module log to the AI analysis, can you help me to see that these problems mentioned are possible to solve the problem?The following reply:
> 
> From the error log you provided, the crash occurred in an activity called SplashScreenActivity. This activity tried to load a layout file containing a CircularProgressIndicator component, but encountered problems. The specific error is:
> 
> java
> java.lang.RuntimeException: Unable to start activity ComponentInfo{sh.siava.pixelxpert/sh.siava.pixelxpert.ui.activities.SplashScreenActivity}: android.view.InflateException: Binary XML file line #52 in sh.siava.pixelxpert:layout/activity_splash_screen: Binary XML file line #52 in sh.siava.pixelxpert:layout/activity_splash_screen: Error inflating class com.google.android.material.progressindicator.CircularProgressIndicator
> Here are some possible reasons for this issue:
> 
> Layout File Problem: There may be errors or incomplete attribute settings for the CircularProgressIndicator in line 52 of the XML layout file.
> Dependency Library Issue: If your application has not correctly added the Google Material Design library, the CircularProgressIndicator class will not be found, causing inflation to fail.
> Version Compatibility Issue: Your application may be using APIs that are incompatible with the Android version on the current device. For example, if CircularProgressIndicator was introduced in a higher version of the Android API and you run your app on a lower version of the Android system, such issues may occur.
> Third-Party Module Conflict: If you're using LSPosed or other modules to modify system functionality or behavior, these modules may interfere with the normal operation of native components, leading to similar issues.
> To solve this problem, you can try the following steps:
> 
> Check the XML layout file for SplashScreenActivity to ensure that the CircularProgressIndicator tag on line 52 is correct.
> Make sure that your project has added the Google Material Design library as a dependency.
> If you're using third-party modules, try disabling them to see if it solves the problem.
> Clean and rebuild your project to clear any potential build errors.
> If the above steps don't solve the problem, please provide more information like the detailed layout file content, project dependencies, etc., for further analysis.
> 
> 

All components used in the app are already included in app dependencies and built in the apk already. This can't be the case normally. Unless there's a bug in one of dependencies

**Comment by Mahmud0808** [comment]
Fixed in 8f5e7dbcec5fe4f58aca7ba57aa9dfb567ab862b

Re-open if you are sill facing the same issue.

**Comment by fuzhengqu** [comment]
> Fixed in [8f5e7db](https://github.com/siavash79/PixelXpert/commit/8f5e7dbcec5fe4f58aca7ba57aa9dfb567ab862b)
> 
> Re-open if you are sill facing the same issue.

I couldn't wait to install the latest version 309, but the problem is still the same😂
[Uploading LSPosed_2023-12-10T13_12_11.498977.zip…]()

**Comment by fuzhengqu** [comment]
[LSPosed_2023-12-10T13_12_11.498977.zip](https://github.com/siavash79/PixelXpert/files/13626846/LSPosed_2023-12-10T13_12_11.498977.zip)

**Comment by KaiRivers** [comment]
> There is also a strange problem, I clearly installed the 3.2.0 version, why is the app info displayed 3.1.0!

I noticed this too. I found a fix. I downloaded stable 3.2.0 zip file, opened it with file explorer and installed the apk file inside. It will say that the app will be updated so just accept that and the app will open with no problem.

**Comment by fuzhengqu** [comment]
> > There is also a strange problem, I clearly installed the 3.2.0 version, why is the app info displayed 3.1.0!
> 
> I noticed this too. I found a fix. I downloaded stable 3.2.0 zip file, opened it with file explorer and installed the apk file inside. It will say that the app will be updated so just accept that and the app will open with no problem.

According to the method you mentioned, I downloaded the 3.2 compressed package. After decompressing it, I installed the apk file inside. After installation, it can indeed be opened normally. I installed the latest canary version through the update function in the app, and it was normal. I installed all the other magisk modules back and there was no problem. This shows that there is indeed a bug in Pixel Xpert itself. I hope developers can find the problem and fix the bug as soon as possible

**Comment by EleoXDA** [comment]
> > > There is also a strange problem, I clearly installed the 3.2.0 version, why is the app info displayed 3.1.0!
> > 
> > 
> > I noticed this too. I found a fix. I downloaded stable 3.2.0 zip file, opened it with file explorer and installed the apk file inside. It will say that the app will be updated so just accept that and the app will open with no problem.
> 
> According to the method you mentioned, I downloaded the 3.2 compressed package. After decompressing it, I installed the apk file inside. After installation, it can indeed be opened normally. I installed the latest canary version through the update function in the app, and it was normal. I installed all the other magisk modules back and there was no problem. This shows that there is indeed a bug in Pixel Xpert itself. I hope developers can find the problem and fix the bug as soon as possible

if installing apk fixes the problem then it is a random bug that appears once in 100 times. There is already a note in our telegram group about it.

**Comment by Nadyita** [comment]
I've been having the exact same issue since one of the last Magisk-Alpha-Upgrades (~2 weeks ago). Using the 3.2.0 apk works, every canaray apk is on a crash-loop. Before that, the Magisk-upgrade actually made the whole LSPosed module disappear and it was only with one of the latter updates that the module (and crashing apk) came back,
